---
title: "Activity 2"
output: github_document
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Day 1


```{r load_packages}

library(tidyverse)
library(tidymodels)

```


```{r load_data}

music_50s <- read.csv("1950[1].csv")

music_60s <- read.csv("1960[1].csv")

music_70s <- read.csv("1970[1].csv")

music_80s <- read.csv("1980[1].csv")

music_90s <- read.csv("1990[1].csv")

music_00s <- read.csv("2000[1].csv")

music_10s <- read.csv("2010[1].csv")
```


```{r}

music <- rbind(music_50s, music_60s, music_70s, music_80s, music_90s, music_00s, music_10s)
```


```{r}
ggplot(music, aes(x = bpm))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = nrgy))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = dnce))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = dB))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = live))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = val))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = dur))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = acous))+
        geom_histogram()
```


```{r}
ggplot(music, aes(x = spch))+
        geom_histogram()
```


```{r}

ggplot(music, aes(x = bpm, y = pop))+ 
  geom_point()

cor(music$bpm, music$pop)
```


```{r}

ggplot(music, aes(x = nrgy, y = pop))+ 
  geom_point()

cor(music$nrgy, music$pop)
```


```{r}

ggplot(music, aes(x = dnce, y = pop))+ 
  geom_point()

cor(music$dnce, music$pop)
```


```{r}

ggplot(music, aes(x = dB, y = pop))+ 
  geom_point()

cor(music$dB, music$pop)
```


```{r}

ggplot(music, aes(x = live, y = pop))+ 
  geom_point()

cor(music$live, music$pop)
```


```{r}

ggplot(music, aes(x = val, y = pop))+ 
  geom_point()

cor(music$val, music$pop)
```


```{r}

ggplot(music, aes(x = dur, y = pop))+ 
  geom_point()

cor(music$dur, music$pop)

```


```{r}

ggplot(music, aes(x = acous, y = pop))+ 
  geom_point()


cor(music$acous, music$pop)
```


```{r}

ggplot(music, aes(x = spch, y = pop))+ 
  geom_point()

cor(music$spch, music$pop)
```

```{r}

lm_spec <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

```


```{r}

slr_mod <- lm_spec %>% 
  fit(data = music, pop ~ dB)

tidy(slr_mod)
```

$$
pop = 74.8 +  1.37 \times dB
$$
1. The intercept is 74.8. This means a song with dB = 0 would have a popularity of 74.8.

2. The slope is 1.37. This means that for each 1 unit increase in dB the populatity will increase by 1.37 units. 

##Day 2



```{r splitting_the_data}

set.seed(123)

music_split <- initial_split(music, 0.8)

music_train <- training(music_split)

music_test <- testing(music_split)

```


```{r}

lm_spec <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

```

```{r}

slr_mod2 <- lm_spec %>% 
  fit(data = music_train, pop ~ dB)

tidy(slr_mod2)
```

```{r}

glance(slr_mod2)

```

```{r pred-df}
pred_df <- tibble::tibble(
  dB = 0:10
)
```

```{r predict}

pred_df %>% 
  mutate(
    pred_value = predict(slr_mod2, new_data = pred_df) %>% pull(.pred)
  )
```

```{r augment}
slr_aug <- augment(slr_mod2, new_data = music_test)

slr_aug
```

``` {r }
slr_aug <- augment(slr_mod2, new_data = music_test)
slr_aug
```
